name: Docker Image CI

on:
  push:
    branches: [ master, github-actions-1 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --file Dockerfile1809 --tag iorp/achieve-adagent:1809 .
        docker build --file Dockerfile1803 --tag iorp/achieve-adagent:1803 .
    - name: Publish on dockerhub
      run: |
        echo  ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_HOST }}
        docker push iorp/achieve-adagent:1809
        docker push iorp/achieve-adagent:1803
      
